REGIONS = {
    "Toshkent": ["toshkent", "angren", "piskent", "bekobod", "parkent", "gazalkent", "olmaliq", "boka", "yangiyol", "nurafshon"],
    "Andijon": ["andijon", "xonobod", "shahrixon", "xojaobod", "paxtaobod", "asaka", "marhamat", "paytug"],
    "Farg‘ona": ["fargona", "qoqon", "margilon", "bogdod", "oltiariq", "quva", "rishton"],
    "Namangan": ["namangan", "chortoq", "chust", "pop1", "uchqorgon", "mingbuloq"],
    "Samarqand": ["samarqand", "ishtixon", "mirbozor", "kattaqorgon", "urgut"],
    "Buxoro": ["buxoro", "gazli", "gijduvon", "qorakol", "jondor"],
    "Qashqadaryo": ["qarshi", "dehqonobod", "muborak", "shahrisabz", "guzor"],
    "Surxondaryo": ["termiz", "boysun", "denov", "sherobod", "shorchi"],
    "Jizzax": ["jizzax", "zomin", "forish", "gallaorol", "dostlik"],
    "Navoiy": ["navoiy", "zarafshon", "konimex", "nurota", "uchquduq"],
    "Xorazm": ["urganch", "hazorasp", "xonqa", "yangibozor", "shovot", "xiva", "boston"],
    "Sirdaryo": ["guliston", "sardoba", "sirdaryo", "boyovut"],
    "Qoraqalpog‘iston": ["nukus", "moynoq", "taxtakopir", "tortkol", "qongirot"]
}

CITY_NAMES = {
    "toshkent": {"uz": "Toshkent", "kr": "Тошкент", "ru": "Ташкент"},
    "andijon": {"uz": "Andijon", "kr": "Андижон", "ru": "Андижан"},
    "fargona": {"uz": "Farg‘ona", "kr": "Фарғона", "ru": "Фергана"},
    "namangan": {"uz": "Namangan", "kr": "Наманган", "ru": "Наманган"},
    "samarqand": {"uz": "Samarqand", "kr": "Самарқанд", "ru": "Самарканд"},
    "buxoro": {"uz": "Buxoro", "kr": "Бухоро", "ru": "Бухара"},
    "qarshi": {"uz": "Qarshi", "kr": "Қарши", "ru": "Карши"},
    "termiz": {"uz": "Termiz", "kr": "Термиз", "ru": "Термез"},
    "jizzax": {"uz": "Jizzax", "kr": "Жиззах", "ru": "Джизак"},
    "navoiy": {"uz": "Navoiy", "kr": "Навоий", "ru": "Навои"},
    "urganch": {"uz": "Urganch", "kr": "Урганч", "ru": "Ургенч"},
    "guliston": {"uz": "Guliston", "kr": "Гулистон", "ru": "Гулистан"},
    "nukus": {"uz": "Nukus", "kr": "Нукус", "ru": "Нукус"},
    "qoqon": {"uz": "Qo‘qon", "kr": "Қўқон", "ru": "Коканд"},
    "margilon": {"uz": "Marg‘ilon", "kr": "Марғилон", "ru": "Маргилан"},
    "angren": {"uz": "Angren", "kr": "Ангрен", "ru": "Ангрен"},
    "bekobod": {"uz": "Bekobod", "kr": "Бекобод", "ru": "Бекабад"},
    "shahrisabz": {"uz": "Shahrisabz", "kr": "Шаҳрисабз", "ru": "Шахрисабз"},
    "denov": {"uz": "Denov", "kr": "Денов", "ru": "Денау"},
    "zarafshon": {"uz": "Zarafshon", "kr": "Зарафшон", "ru": "Зарафшан"},
    "xiva": {"uz": "Xiva", "kr": "Хива", "ru": "Хива"},
    "pop1": {"uz": "Pop", "kr": "Поп", "ru": "Пап"},
}